baseURL = "https://hophamlam.com"
languageCode = "en-us"
title = "hophamlam"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[params]
env = "production"
title = "hophamlam"
description = "hophamlam's profile"
keywords = ["hophamlam", "ho pham lam", "lam ho", "Há»“ Pháº¡m LÃ¢m", "Profile", "Blog", "Portfolio"]
author = "hophamlam"
DateFormat = "January 2, 2006"
defaultTheme = "auto"
ShowReadingTime = false
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
UseHugoToc = true
disableSpecial1stPost = true
hideMeta = true

[params.profileMode]
enabled = true
title = "hophamlam"
subtitle = "ğŸ‘ªğŸšğŸ’ğŸµğŸ’»âš½ğŸ‡»ğŸ‡³"
imageUrl = "https://gravatar.com/avatar/8bcd691b08c9cd64eb566272afee38c4?size=512"
imageWidth = 300
imageHeight = 300
imageTitle = "Ho Pham Lam"

[[params.socialIcons]]
name = "zalo"
url = "https://zalo.me/0938568040"

[[params.socialIcons]]
name = "messenger"
url = "https://www.messenger.com/t/@hophamlam0627"

[[params.socialIcons]]
name = "telegram"
url = "https://t.me/hophamlam"

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 20

[params.assets]
favicon = "/favicon.ico"
favicon16x16 = "/favicon-16x16.png"
favicon32x32 = "/favicon-32x32.png"
apple_touch_icon = "/apple-touch-icon.png"